### ISSUE TITLE
detect if cluster is stable?

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#188] opened 2019-12-06 17:21 UTC
I ran into an issue where I had flapping servers.  I had three nodes and they were all randomly rebooting.  Now fundamentally the issue is caused by me because I run the dqlite server and client in the same process.  So what would happen is the process would start the dqlite server and then my client logic would try to connect and fail, so we kill the process startup.  To mitigate this issue the intention was to start the dqlite server, then wait until it seems like the server is healthy (quorum is reached) and then start the client.  It seemed that logic would avoid the flapping.

The problem is trying to detect if the cluster is stable.  I first was just waiting for FindLeader method to return successful, but that didn't seem sufficient.  I then tried to do a conn.Ping() from the dqlite goland SQL driver, but that seems to be a no-op.  I then did a "SELECT 1" on startup but as soon as I did that in this error situation I would get an assertion failure in dqlite C code that would exit the program. https://github.com/canonical/dqlite/blob/744c4111b3ad202584d86ae742c45e7a315488a8/src/leader.c#L257 In the end I couldn't figure out the right way to detect that the cluster was healthy.

**Comment by freeekanayaka** [comment] 2019-12-06 20:37
Ok, the last assertion failure means there is a bug in dqlite, where (presumably in consequence of some unexpected scenario) we close the SQLite db without cleaning up properly (e.g. closing prepared statements, or ongoing queries etc).

Running the dqlite server and client in the same process should be perfectly fine, and indeed it's what I'd expect people to normally do. Why do you think that's problematic? Of course the client must be able to retry, and not give up killing the entire process if it fails, if that's what you meant.

To detect that the cluster is stable, calling ```db.Ping()``` should be a good strategy for the setting initial process state. Why does that end up in a no-op for you? It should succeed only once the cluster has a leader.

All that being said, I think there is a bug where if you don't run queries like "CREATE IFNOT EXISTS my_table ...``` **before** queries like "SELECT * FROM my_table", then the SELECT might fail with a "table does not exist" error. But that probably doesn't apply to your situation, so I'm just mentioning it as a heads up.

**Comment by ibuildthecloud** [comment] 2019-12-10 23:57
`db.Ping()` just seemed to work even when things were not healthy and would result in the that `assert` failure above.

I currently have a cluster that is stuck with three nodes rebooting because they keep hitting `Assertion failed: rc == 0 (src/leader.c: leader__close: 257)` on start.  Is there anything you would want to know to debug this?

**Comment by ibuildthecloud** [comment] 2019-12-11 00:10
Also, prior to to this cluster getting into this situation, two of the node were failing non-stop with `bad connection` error while doing the below sanity test
```golang
func ping(ctx context.Context, db *sql.DB) error {
	row, err := db.QueryContext(ctx, "SELECT 1")
	if err != nil {
		return err
	}
	defer row.Close()

	row.Next()
	return row.Err()
}
```

**Comment by freeekanayaka** [comment] 2019-12-11 10:38
I've added a test in #66 to confirm that ```db.Ping()``` returns an error if there's no leader, and returns no error if there's one. So that should be either a red herring or your particular scenario is somehow different than the test.

However ```db.Ping()``` makes use of connections internally cached by the db Go package, so if you call ```db.Ping()``` twice, it will return no error, even if the cluster lost a leader between those calls.

That's confirmed by the unit test as well, not sure if that applies to you.

As per the ```bad connection``` error, that is a ```driver.ErrBadConn``` that is returned by the dqlite driver implementation mostly when there is no leader available. In that case the transaction should be retried by the client code, using some backoff.

Finally, the assertion failure seems to be the bug here. If you can reproduce it reliably, would it be possible to attach or send me a tarball with reproducing data and code or equivalent info?

**Comment by ibuildthecloud** [comment] 2019-12-11 16:17
@freeekanayaka I'll try to send the data of a failing cluster.  How can I send it to you?  My email is darren@rancher.com if you'd like to share your email.

Regarding db.Ping().  I want to clarify that this is a proper way to ensure a stable setup.  Typically in a go you open the DB once (`sql.Open()`) and then never call `db.Close()`.  So on startup the idiomatic approach in go would be the following:

```golang
db, err := sql.Open(driver, datasource)
if err != nil {
     return err
}
for db.Ping() != nil {
  time.Sleep(time.Second)
}
```
Does this seem like a sane approach?

Also, regarding `bad connection`.  If I get that error, do I have to do `db.Close()` and the `sql.Open()` to recover?  Again, that is not an expected flow in go.

**Comment by freeekanayaka** [comment] 2019-12-11 16:36
> @freeekanayaka I'll try to send the data of a failing cluster. How can I send it to you? My email is [darren@rancher.com](mailto:darren@rancher.com) if you'd like to share your email.

free.ekanayaka@canonical.com

> 
> Regarding db.Ping(). I want to clarify that this is a proper way to ensure a stable setup. Typically in a go you open the DB once (`sql.Open()`) and then never call `db.Close()`. So on startup the idiomatic approach in go would be the following:
> 
> ```go
> db, err := sql.Open(driver, datasource)
> if err != nil {
>      return err
> }
> for db.Ping() != nil {
>   time.Sleep(time.Second)
> }
> ```
> 
> Does this seem like a sane approach?

It does seem sane to me, and it's virtually what we do in LXD.
 
> Also, regarding `bad connection`. If I get that error, do I have to do `db.Close()` and the `sql.Open()` to recover? Again, that is not an expected flow in go.

No you don't have too. If a driver returns ```ErrBadConn``` the ```sql``` package will internally invalidate that connection. All you need to do is to retry your query (e.g. ```db.Exec```, ```tx.Exec``` or whatever).

**Comment by ibuildthecloud** [comment] 2019-12-11 18:49
I've changed my logic on start to just rely on db.Ping() now to test that things are stable.  I also upgraded from v1.1.0 to v1.2.0 and latest libco, raft, sqlite as of now.  It seems upgrading to the latest has fixed something because things now have come up on my broken cluster.  I'll see how it goes.  Typically the cluster crashes within a 1-3 days.

**Closed** 2019-12-11 18:51 UTC
